### ISSUE TITLE
[Question] JWT in DF really stateless or not ?!

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/df-core#16]
So I needed to put some custom info into the JWT being returned on user login (or refresh).

So in the post-event I do
```
$token = \DreamFactory\Core\Utility\Session::getSessionToken();
$payloadArray = \JWTAuth::manager()->getJWTProvider()->decode($token);
$payloadArray['foo'] = "bar";
$token = \JWTAuth::manager()->getJWTProvider()->encode($payloadArray);

$event['response']['content']['session_token'] = $token;
$event['response']['content']['session_id'] = $token;
$event['response']['content_changed'] = true;
```

Works fine so far. Token has new info added and is signed with APP_KEY again.

When reading `df-core\src\Utility\JWTUtilities.php` I saw it saves/deletes the token to `DB::table('token_map')` :scream: 

Now the big question: Why does it save the token to DB if its supposed to be stateless? Do I need to update those records with my changed token to not mess up DF functionalities? (If so, are there any other places I need to update?)

**Comment by a15lam** [comment]
@philicious, as far as the session itself is concerned, it is stateless. We store the user-to-token relation in the table so that, if after establishing a session (JWT) for a user, the user is deactivated  or changes his/her password, we could then also deactivate all active tokens for that user. If we do not do this then the user will continue to have access even after changing password or being deactivated until the token expires or never in case of a 'forever' token.

**Comment by philicious** [comment]
@df-arif sounds legit and makes sense.
So should I update those DB records then or is it save if the user token doesnt match the value in DB anymore? 
As far as I could tell from JWTUtilities code, its never getting/comparing the token from that table. Dunno about other codes of DF tho.

(The reason I wanna edit the JWT is to add custom data to it so it can be easily used in customs scripts without having to call the DB for "user/custom" or similar. Also caching in memory wouldnt be the best idea imho)

**Comment by a15lam** [comment]
@philicious, Things will still function without any error if you do not update the table. However, I would recommend updating that 'token_map' table (update records with old token with the new one) otherwise the system will not be able to deactivate tokens when related user/app/role is deactivated/deleted.

**Comment by philicious** [comment]
@df-arif thank you very much for the info. appreciated !! I'll do as advised then :+1:

**Comment by philicious** [comment]
For the sake of completeness and for future readers, find my implementation here http://www.devops-blog.net/dreamfactory/adding-custom-session-data-to-dreamfactory-jwt-token
